import { RepositoryWithStats } from '@/types/repository';

export const PLACEHOLDER_REPOS: RepositoryWithStats[] = [
  {
    id: '1',
    github_id: 101,
    full_name: 'ethereum/go-ethereum',
    name: 'go-ethereum',
    owner_login: 'ethereum',
    owner_avatar_url: 'https://avatars.githubusercontent.com/u/6250754?v=4',
    description: 'Official Go implementation of the Ethereum protocol, allowing developers to build decentralized web3 applications.',
    language: 'Go',
    topics: ['web3', 'blockchain', 'ethereum', 'p2p'],
    stars_count: 45201,
    forks_count: 18450,
    issues_count: 312,
    github_created_at: '2013-12-26T00:00:00Z',
    github_updated_at: new Date().toISOString(),
    github_pushed_at: new Date().toISOString(),
    license_spdx: 'LGPL-3.0',
    is_archived: false,
    last_synced_at: new Date().toISOString(),
    stars_gained_24h: 142,
    stars_gained_7d: 890,
    trending_score: 98.5,
  },
  {
    id: '2',
    github_id: 102,
    full_name: 'eclipse/mosquitto',
    name: 'mosquitto',
    owner_login: 'eclipse',
    owner_avatar_url: 'https://avatars.githubusercontent.com/u/567243?v=4',
    description: 'Eclipse Mosquitto - An open source MQTT broker for the Internet of Things (IoT).',
    language: 'C',
    topics: ['iot', 'mqtt', 'broker', 'c'],
    stars_count: 8104,
    forks_count: 2400,
    issues_count: 89,
    github_created_at: '2010-06-15T00:00:00Z',
    github_updated_at: new Date().toISOString(),
    github_pushed_at: new Date().toISOString(),
    license_spdx: 'EPL-2.0',
    is_archived: false,
    last_synced_at: new Date().toISOString(),
    stars_gained_24h: 45,
    stars_gained_7d: 210,
    trending_score: 85.2,
  },
  {
    id: '3',
    github_id: 103,
    full_name: 'vercel/next.js',
    name: 'next.js',
    owner_login: 'vercel',
    owner_avatar_url: 'https://avatars.githubusercontent.com/u/14985020?v=4',
    description: 'The React Framework for the Web.',
    language: 'TypeScript',
    topics: ['react', 'nextjs', 'framework'],
    stars_count: 120500,
    forks_count: 25100,
    issues_count: 1200,
    github_created_at: '2016-10-25T00:00:00Z',
    github_updated_at: new Date().toISOString(),
    github_pushed_at: new Date().toISOString(),
    license_spdx: 'MIT',
    is_archived: false,
    last_synced_at: new Date().toISOString(),
    stars_gained_24h: 320,
    stars_gained_7d: 2100,
    trending_score: 99.9,
  }
];

export const PLACEHOLDER_DOMAINS = [
  { id: '1', name: 'Web3 & Blockchain', slug: 'web3-blockchain', count: 1205 },
  { id: '2', name: 'Internet of Things', slug: 'iot', count: 854 },
  { id: '3', name: 'Artificial Intelligence', slug: 'artificial-intelligence', count: 4320 },
  { id: '4', name: 'Web Development', slug: 'web-development', count: 8900 },
];
